before:
  hooks:
    - go mod tidy
    - go generate ./..

builds:
  - env:
      - CGO_ENABLED=0
    main: ./AVMeta.go
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
      - arm
      - 386
      - ppc64le
      - s390x
      - mips64
      - mips64le
    goarm:
      - 6
      - 7
    gomips:
      - hardfloat
    ignore:
      - goos: darwin
        goarch: 386
    ldflags: -s -w -X main.version={{ .Version }} -X main.commit={{ .ShortCommit }} -X main.date={{ .Date }}

archives:
  - format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "snapshot-{{ .Commit }}"

release:
  prerelease: auto
  name_template: "{{ .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pll request
      - Merge branch

brews:
  - github:
    owner: ylqjgm
    name: homebrew-tap
  folder: Formula
  homepage: "https://githb.com/ylqjgm/AVMeta"
  descript: "一个使用 Go 语言开发的 AV 元数据刮削器"
  skip_upload: false
  install: |
    bin.install "AVMeta"